import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import logomark from "public/logo.svg";

export default function Home() {
  return (
    <div className="h-screen w-screen flex justify-center items-center bg-slate-800">
      <Head>
        <title>This is a next app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/playground" passHref>
        <button>Playground</button>
      </Link>
      <div className="bg-slate-200 shadow-lg shadow-sky-500/30 flex flex-row justify-between items-center gap-5 p-3 rounded-xl">
        <Image src={logomark} alt="#" />
        <p className="font-bold px-2 p-1 text-slate-600 bg-slate-300 rounded-full shadow-lg shadow-sky-500/30">
          v3.0.0
        </p>
      </div>
    </div>
  );
}
